services:
  mariadb:
    image: mariadb
    container_name: mariadba4
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: pruebapass
      MARIADB_ROOT_USER: agent
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: PEPS
    volumes:
      - mariadb_dataa4:/var/lib/mysql
      - ./coches.sql:/docker-entrypoint-initdb.d/coches.sql
    user: mysql
    
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmina4
    restart: always
    environment:
      PMA_HOST: mariadb
    ports:
      - 7004:80
    depends_on:
      - mariadb
  # apache:
  #   container_name: apachea4
  #   build: ./apache
  #   ports:
  #     - 6004:80

  python:
    build: .
    container_name: python
    environment:
      PYTHONUNBUFFERED: 1
      DB_USERNAME: root
      DB_PASSWORD: pruebapass
      DB_DATABASE: PEPS
      DB_HOST: mariadb
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
      SALT: SALT
    depends_on:
        - mariadb
  
  apache-waf:
    build: ./waf/
    ports:
      - 6014:443
      - 6004:80
    depends_on:
      - python
    links:
      - python
    volumes:
      - ./logwaf:/var/log/apache2
    
volumes:
  mariadb_dataa4:
